### ISSUE TITLE
Javascript content creation

### ISSUE THREAD

**Issue by tahminarasoli** [rago89/Group-6-Study-Guide#3]
- [ ] Planing content for each section of the menu
- [ ] Create simplistic ans explicit examples to each module 
- [ ] Create a branch named according of the content thar is going to be uploaded
- [ ] Work on forked index.html file
- [ ] Work on forked style.css file
   - Work with @media Query to make the web responsive
- [ ] Work in the section `content` according to the [figma planing design](https://www.figma.com/file/YYy5dIh0y1hGHIhZeKZy32/Study-Guide-HYF-Group-6?node-id=0%3A1)
- [ ] Create a branch for each example
- [ ] Change your status in the project, to follow the work

**Comment by tahminarasoli** [comment]
@rago89 can you please add Brain to repository contributors as well as in this issue. thanks

**Comment by rago89** [comment]
> contributors as well as in this issue. thanks

I'm waiting that he accepts the invitation to add him
